### ISSUE TITLE
Hello Issue

### ISSUE THREAD

**Issue by mohammedasker** [kapunahelewong/git-playground#20]
I'm testing this feature so I will close it shortly. I'll later create a new issue that requires a solution to my problem. :)

**Comment by kapunahelewong** [comment]
Great! Let me know if you have any questions. I'll add some labels just for fun :)

**Comment by mohammedasker** [comment]
Sure! My only question now is how can I help to contribute to this project?

**Comment by kapunahelewong** [comment]
Well, it's pretty flexible. The only caution is to not make a very complicated PR because we want the repo to stay simple for beginners. Here are a couple of ideas:

You could create a twitter handles page where you add your own twitter handle along with an intro paragraph that says something like, "hey contributors, add your twitter handle (or gh handle)". 

You could alternatively write a few paragraphs of text in a new file with lots of typos. You could use just made up things you write on the spot, or some piece of classical literature - it just has to be in the public domain.

So things that are really simple are good. We want first time contributors to see things they can fix or add that are easy since they'll be contending with the whole process of submitting the PR, which can take a lot of attention to detail the first few times. So we want them to be able to focus on the process, rather than being concerned about whether something will compile. Does that help?

**Comment by mohammedasker** [comment]
Yes, that helps me a lot! Now I know what I'm going to do next.
